### PR TITLE
submit to CRAN

### PR DESCRIPTION
**Pull request by roninsightrx**
Added a news.md for the release. Only needs a cran.md, and then ready for release to CRAN.

### CODE REVIEW

**Comment by karawoo** [comment]
rhub turned up the following, as well as a couple more URL issues (some returning a 403 error, but I don't see that when I try to visit them 😕 )

Screen Shot 2022-05-05 at 12 04 39 PM

**Comment by roninsightrx** [comment]
> rhub turned up the following, as well as a couple more URL issues (some returning a 403 error, but I don't see that when I try to visit them 😕 )
> 
> Screen Shot 2022-05-05 at 12 04 39 PM

Shall we just explain in CRAN notes that they URLs are fine?

**Comment by roninsightrx** [comment]
> Shall we just explain in CRAN notes that they URLs are fine?

Ah you did, nm.

**Review by karawoo — APPROVED** [review]
I have submitted this version to CRAN 🤞

**Pull request merged**
